<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://samples.lauerbach.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="SimpleWebServiceImplService" targetNamespace="http://samples.lauerbach.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://samples.lauerbach.com/" elementFormDefault="unqualified" targetNamespace="http://samples.lauerbach.com/" version="1.0">

  <xs:element name="hallo" type="tns:hallo"/>

  <xs:element name="halloResponse" type="tns:halloResponse"/>

  <xs:complexType name="hallo">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="halloResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="hallo">
    <wsdl:part element="tns:hallo" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="halloResponse">
    <wsdl:part element="tns:halloResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="SimpleWebService">
    <wsdl:operation name="hallo">
      <wsdl:input message="tns:hallo" name="hallo">
    </wsdl:input>
      <wsdl:output message="tns:halloResponse" name="halloResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SimpleWebServiceImplServiceSoapBinding" type="tns:SimpleWebService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hallo">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="hallo">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="halloResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SimpleWebServiceImplService">
    <wsdl:port binding="tns:SimpleWebServiceImplServiceSoapBinding" name="SimpleWebServiceImplPort">
      <soap:address location="http://localhost:8080/SimpleWebService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>